### ISSUE TITLE
Build error because of CommonComponentProps

### ISSUE THREAD

**Issue by djshubs** [stripe/react-connect-js#107]
My builds started to fail because of onLoadError and onLoaderStart now being required props. However, the docs say they're optional. 

Link - https://docs.stripe.com/connect/supported-embedded-components/payment-details

what is expected behavior here? and what's the purpose of the onLoadError and onLoaderStart? 

```tsx
        <ConnectPaymentDetails
          payment={paymentId}
          onClose={() => setOpen(false)}
          key={paymentId}
          onLoadError={({ error, elementTagName }: LoadError) => {
            console.log('Error loading payment details', error);
            captureException({ error, elementTagName });
          }}
          onLoaderStart={() => undefined}
        />

**Comment by jorgea-stripe** [comment]
Hey @djshubs , thanks for reporting! They are optional. We'll fix this issue.

**Comment by jorgea-stripe** [comment]
This has been published now, apologies for the break!
