### ISSUE TITLE
ConnectNotificationBanner Styling bug

### ISSUE THREAD

**Issue by matthewo-gl** [stripe/react-connect-js#121]
Hello I'm trying to use the ConnectNotificationBanner component but I'm running into a UI issue with the component

I'm only passing the colorBackground: '#FFFFFF' to the stripe instance but I see  two issues, see video and screenshot.

https://github.com/user-attachments/assets/b0a19883-b4ab-482e-a415-b5151ebb0843

<img width="998" alt="image" src="https://github.com/user-attachments/assets/571dabd0-2f84-418a-b3fb-ba21782f1a89">

1. One issue is that the component shows a container with a white background while it's still loading
2. The other issue is that the component has a white background outside of the border which I would like to be removed

Is there a way to resolve these issues by passing in any props to appearance.variables?

Here's the package versions I'm using if it's useful
```
    "@stripe/connect-js": "^3.3.13",
    "@stripe/react-connect-js": "^3.3.14",
```

**Comment by jorgea-stripe** [comment]
Check out this demo: https://docs.corp.stripe.com/connect/customize-connect-embedded-components
![image](https://github.com/user-attachments/assets/77eb2256-b890-4cf6-a469-955ce735d99c)

Are you sure you are setting the `colorBackground` in the right connect instance that corresponds to this component? Are any other appearance parameters working?

**Comment by jorgea-stripe** [comment]
If you think this is an issue, please provide a repro repo and reactivate!
