### ISSUE TITLE
Unable to use react@18 and @stripe/connect-js@1.1.0

### ISSUE THREAD

**Issue by utyfua** [stripe/react-connect-js#28]
Hello

I have an issues related to versions of peer dependencies.

I want to use `@stripe/connect-js@1.1.0` for [customizing](https://stripe.com/docs/connect/customize-connect-embedded-components). But I cant due to dependency conflict with `@stripe/react-connect-js@1.4.0`.

Also I have `react@18` but I cannot install `@stripe/react-connect-js@1.4.0` due to dependency conflict.
But according to [this PR](https://github.com/stripe/react-connect-js/pull/26) I should be able to use it.

I also want to thank you for the library itself. Easy and powerful at the same time.

**Comment by mertindervish** [comment]
Just submitted a PR that could fix this problem https://github.com/stripe/react-connect-js/pull/33
@jojo-stripe I think the PR could be helpful to support newer version of React

**Comment by mertindervish** [comment]
By the way temporarily my changes from the PR can be used like this in the `project.json` before the merge:
```json
"@stripe/connect-js": "1.1.0",
"@stripe/react-connect-js": "https://git@github.com/mertindervish/react-connect-js#7b55f99f896f39ef62c4e7488eec5891f0e6f73d",
```

**Comment by utyfua** [comment]
Looks like the issue resolved but I have another one so I will open another issue for that.
