### ISSUE TITLE
ConnectPaymentDetails does not support visible prop

### ISSUE THREAD

**Issue by ljrahn** [stripe/react-connect-js#69]
I see in your examples, and even in the documentation, you pass a visible prop, but the component doesn't accept it. Even if I try to wrap a piece of state around the component, toggle visibility using some onClick handler, then set the state to false using the onClose handler provided by the ConnectPaymentDetails component, the payment details popup doesn't disappear. ie. I don't see any way to close the component once its open.

![image](https://github.com/stripe/react-connect-js/assets/56951251/6cccf139-f5c1-4754-afc6-a34b3d1669e0)

**Comment by jorgea-stripe** [comment]
We've since fixed this - the visible prop was removed from our beta a while ago, it is no longer needed! Simply stop rendering the component with a react conditional, like so:
```
{{visible ? <ConnectPaymentDetails ... /> : null }}
```

Or pass in a null `payment`.
