### ISSUE TITLE
Onboarding Component suddenly requires opening a new window to gather information

### ISSUE THREAD

**Issue by goguda** [stripe/react-connect-js#88]
I had the onboarding component working perfectly with our implementation, with the form showing as an iframe right in our website (as expected), but now all of a sudden I'm not getting the form anymore.

Instead I'm getting this button to "Add information", and when clicked, it opens the form in a new window, completely unstyled (and I'm not even sure that it's the right form):

![add_information_button](https://github.com/stripe/react-connect-js/assets/26887502/05f0c439-225c-4f0e-a81b-96317a1cfae4)

![onboarding_form_in_new_window](https://github.com/stripe/react-connect-js/assets/26887502/32a0f641-3c89-4146-ba9a-466948e35bad)

Nothing has changed in our implementation since it was working a couple weeks ago. I've tried downgrading to different versions of @stripe/connect-js and @stripe/react-connect-js with no luck, same issue regardless of version, which makes me wonder if there's been a change to the iframe that's being loaded in server-side.

This is our code, which is based on the example in the Stripe documentation:

```
const StripePayoutOnboarding: React.FC<StripePayoutOnboardingProps> = (props) => {

    const { UserSettings } = React.useContext(UserSettingsContext);

    const [stripeConnectInstance] = React.useState(() => {
        const fetchClientSecret = async () => {
          // Fetch the AccountSession client secret
          const response = await fetch(`http://iroomit.gogudanetwork.com:3000/payments/connected/getAccountSession`, {
              method: 'POST',
              headers: {
                'content-type': 'application/json'
              },
              body: JSON.stringify({
                session: UserSettings.sessionId
              })
            });
          if (!response.ok) {
            // Handle errors on the client side here
            const {error} = await response.json();
            console.log('An error occurred: ', error);
            return undefined;
          } else {
            const token = await response.text();
            console.log(token);
            return token;
          }
        }
        return loadConnectAndInitialize({
            // This is your test publishable API key.
            publishableKey: process.env.NEXT_PUBLIC_STRIPE_API_KEY,
            fetchClientSecret: fetchClientSecret,
            
            appearance: {
              overlays: 'dialog',
              variables: {
                spacingUnit: '12px',
                colorPrimary: '#000000',
                borderRadius: '4px',
                formHighlightColorBorder: '#000000',
                colorBorder: '#a0a0a0',
                buttonPrimaryColorBackground: Colors.primary,
                buttonPrimaryColorBorder: Colors.primary,
                actionPrimaryColorText: Colors.primary,
                formAccentColor: Colors.primary
              },
            },
          })
        });
    
      return (
              <ConnectComponentsProvider connectInstance={stripeConnectInstance}>
                <ConnectAccountOnboarding onExit={() => {
                    stripeConnectInstance.logout();
                    props.onExit?.();
                }}/>
              </ConnectComponentsProvider>

      )
}
```

And I've made sure the client_secret sent back from the server is valid too:

```
export function getConnectedAccountSession(accId: string) {
  return stripe.accountSessions.create({account: accId, components: {
    payments: {
      enabled: true
    },
    payouts: {
      enabled: true
    },
    account_onboarding: {
      enabled: true
    }
  }
  });
}
```

Again nothing has changed on our end and it was working fine before, which I find very strange. Tested in both Firefox and Chrome with the same results. Any ideas?

**Comment by goguda** [comment]
Nevermind, just read about authentication

**Comment by jorgea-stripe** [comment]
For future reference, here are the doc around [user authentication](https://docs.stripe.com/connect/get-started-connect-embedded-components#user-authentication-in-connect-embedded-components) and around the [external_account_collection ](https://docs.stripe.com/connect/supported-embedded-components/account-onboarding)parameter
