### ISSUE TITLE
Embedded Onboarding Popup Blocked

### ISSUE THREAD

**Issue by kbernst30** [stripe/react-connect-js#93]
I've been following the tutorial for setting up Onboarding with Stripe Connect https://docs.stripe.com/connect/onboarding/quickstart#init-stripe

I have everything set up, and the iFrame that contains the button to "Add Information" displays on the page, but once i click it, i get a Console Error saying the following:

```
AccountOnboarding.tsx:133 Uncaught (in promise) SubmerchantAuthError: Popup is blocked by browser.
    at SubmerchantAuthenticationContext.tsx:436:18
    at new Promise (<anonymous>)
    at SubmerchantAuthenticationContext.tsx:431:14
    at SubmerchantAuthenticationContext.tsx:452:14
    at async SubmerchantAuthenticationContext.tsx:580:17
```

Even so, a popup does indeed open (definitely wasn't blocked) but shows just a loading indicator.

I dug into the code a bit and the issue seems to occur because the call from window.open in the Stripe connect library returns null. And the error message saying "Popup blocked" happens if the result from that call is null. I know this can be a problem with window.open when not initiated directly by a user, but i don't see anyone else having this problem with Stripe and React.

Here is my code for this.. perhaps I'm doing something subtly wrong, even though I followed the tutorial:

```
const createAccountSession = async (accountId: string) => {
  const { data } = await api.post("/payments/sessions", { account: accountId })
  return data
}

const useCreateAccountSession = () => useMutation({
  mutationFn: (accountId: string) => createAccountSession(accountId)
})

const useStripeConnect = (accountId: string) => {
  const { mutate, data, isPending, isError, isSuccess } = useCreateAccountSession()
  const [stripeConnectInstance, setStripeConnectInstance] = useState<StripeConnectInstance>()

  useEffect(() => {
    if (data) {
      setStripeConnectInstance(
        loadConnectAndInitialize({
          publishableKey: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
          fetchClientSecret: () => data.clientSecret,
          appearance: {
            overlays: "dialog",
            variables: {
              colorPrimary: "#635BFF",
            },
          },
        })
      );
    } else {
      mutate(accountId)
    }
  }, [data])

  return stripeConnectInstance;
};

const OnboardSeller = ({ accountId }: OnboardSellerProps) => {

  const stripeConnectInstance = useStripeConnect(accountId)
  const [onboardingExited, setOnboardingExited] = useState(false)

  return (
    <>
      {stripeConnectInstance && (
        <ConnectComponentsProvider connectInstance={stripeConnectInstance}>
          <ConnectAccountOnboarding
            onExit={() => setOnboardingExited(true)}
          />
        </ConnectComponentsProvider>
      )}
    </>
  )
}
```

This happens in all browsers and for all test users I've created.

**Comment by VinnyLimogrid** [comment]
Did you find a solution?

**Comment by jorgea-stripe** [comment]
Unfortunately I am unable to repro this issue at the moment.

Are you able to repro if you use our quickstart to embedded onboarding sample? https://docs.stripe.com/connect/onboarding/quickstart?connect-onboarding-surface=embedded&connect-dashboard-type=none&connect-economic-model=revshare&connect-loss-liability-owner=stripe&connect-charge-type=direct

@VinnyLimogrid @kbernst30 would you be able to attach a video, or a sample repository that is reproing the issue?

**Comment by jorgea-stripe** [comment]
To double check - your site does comply with the CSP and HTTP header requirements - in particular the [Cross-Origin-Opener-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) value?
https://docs.stripe.com/connect/get-started-connect-embedded-components#csp-and-http-header-requirements

**Comment by palfaro91** [comment]
Hi @jorgea-stripe 
I am having the same issue in a Ionic Vue project. It works if I run the project and access it on desktop. I tested it on Chrome and safari and it works well. When I run the same code in an iOS simulator and click the Add Information button it gives me that error. It opens up a Safari window but it just shows the loader.

**Comment by jogonzal** [comment]
From the docs https://docs.stripe.com/connect/get-started-connect-embedded-components?platform=web#supported-browsers

> Connect embedded components are only supported in web browsers and can’t be used in embedded web views inside mobile or desktop applications.

So ionic is not supported. You can however pop the user out into a standalone browser.

**Comment by palfaro91** [comment]
@jogonzal aww man sorry. I must've glossed over that part. I can pop the user to a browser. Is there a specific url that I can guide them to?

**Comment by jorgea-stripe** [comment]
I should also say - we have a beta of our iOS SDK now and that includes embedded onboarding! At the moment it is however constrained to custom accounts only.

https://docs.stripe.com/connect/get-started-connect-embedded-components?platform=ios
